name: CI SmartSchool

on: [push]



jobs:

  backend:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code

        uses: actions/checkout@v4



      - name: Setup Node.js

        uses: actions/setup-node@v4

        with:

          node-version: 20

          # On précise où se trouve le fichier de verrouillage

          cache-dependency-path: backend/package-lock.json 



      - name: Install dependencies

        # On force l'exécution DANS le dossier backend

        run: cd backend && npm install



      - name: Build

        # On force le build DANS le dossier backend

        run: cd backend && npm run build